XGBoost:
  n_estimators: 100          # Number of boosting rounds (trees)
  max_depth: 6              # Maximum depth of each tree (controls model complexity)
  learning_rate: 0.3        # Step size shrinkage used to prevent overfitting (aka eta)
  subsample: 1.0            # Fraction of training samples used per tree (helps reduce overfitting)
  colsample_bytree: 1.0    # Fraction of features (columns) used per tree (helps reduce overfitting)
