artifacts_root: artifacts

data_ingestion:
  host: localhost
  port: 3307
  user: root
  password: mysecret
  database_name: adashi_staging
  root_dir: artifacts/data_ingestion
  local_data_file: artifacts/data_ingestion/data.csv

data_validation:
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion/data.csv
  STATUS_FILE: artifacts/data_validation/status.txt
